#!/usr/bin/env zsh
#
# === {{CMD}}
# === {{CMD}} dev|spec
# === {{CMD}} my special cmd
#
set -u -e -o pipefail

PATH="$PATH:$THIS_DIR/../sh_color/bin"
PATH="$PATH:$THIS_DIR/../my_crystal/bin"
PATH="$PATH:$THIS_DIR/../process/bin"

if [[ -z "$@" ]]; then
  local +x ACTION="specs"
else
  local +x ACTION="$1"; shift
fi

case "$ACTION" in

  specs)
    CMD="clean.cr specs run $@"
    ${=CMD} || :
    process watch "-r src -r specs -r bin" "$CMD"
    ;;

  *)
    local +x cmd="$ACTION $@"
    ${cmd} || :
    mksh_setup watch "-r src -r specs -r bin" ${cmd}
    ;;

esac

