#!/usr/bin/env zsh
#
# === {{CMD}}       # defaults to: "{{BIN}} specs"
#
set -u -e -o pipefail


if [[ -z "$@" ]]; then
  local +x ACTION="$THIS_NAME specs"
else
  local +x ACTION="$1"; shift
fi

case "$ACTION" in

  *)
    local +x cmd="$ACTION $@"
    ${cmd} || :
    process watch "-r src -r specs -r bin" ${cmd}
    ;;

esac

